/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.controlador;
import controlador.controladorEmpresa;
import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author Draxchaos
 */
public class menuUsuario extends javax.swing.JFrame {

    /**
     * Creates new form menuUsuario
     */
    public menuUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnCrudUsuarios = new javax.swing.JButton();
        btnCrudEmpresa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 204));
        jButton1.setText("Cerrar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        btnReporte.setBackground(java.awt.Color.cyan);
        btnReporte.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnReporte.setForeground(new java.awt.Color(51, 51, 51));
        btnReporte.setText("Reporte de clientes");
        btnReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        getContentPane().add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        btnCrudUsuarios.setBackground(java.awt.Color.cyan);
        btnCrudUsuarios.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnCrudUsuarios.setForeground(new java.awt.Color(51, 51, 51));
        btnCrudUsuarios.setText("Usuarios");
        btnCrudUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrudUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrudUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrudUsuariosMouseExited(evt);
            }
        });
        btnCrudUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrudUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrudUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        btnCrudEmpresa.setBackground(java.awt.Color.cyan);
        btnCrudEmpresa.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnCrudEmpresa.setForeground(new java.awt.Color(51, 51, 51));
        btnCrudEmpresa.setText("Clientes");
        btnCrudEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrudEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrudEmpresaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrudEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrudUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrudUsuariosMouseEntered
        // btnCrudUsuarios.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnCrudUsuariosMouseEntered

    private void btnCrudUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrudUsuariosMouseExited
        // btnCrudUsuarios.setBackground(UIManager.getColor("control"));

    }//GEN-LAST:event_btnCrudUsuariosMouseExited

    private void btnCrudUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudUsuariosActionPerformed
        vistaUsuario vu = new vistaUsuario();
        controlador cem = new controlador(vu);
        vu.setVisible(true);
        vu.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCrudUsuariosActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        Reporte r = new Reporte();
        r.setVisible(true);
        r.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnReporteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        vistaPrincipal l = new vistaPrincipal();
        l.setVisible(true);
        l.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCrudEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudEmpresaActionPerformed
         vistaEmpresa ve = new vistaEmpresa();
        controladorEmpresa cem = new controladorEmpresa(ve);
        ve.setVisible(true);
        ve.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCrudEmpresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCrudEmpresa;
    public javax.swing.JButton btnCrudUsuarios;
    public javax.swing.JButton btnReporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
